// 이 파일은 참조용 원본 데이터입니다.
// 실제 앱에서는 /src/app/App.tsx에 통합된 데이터를 사용합니다.

export const BODY_GROUPS = {
  head: { id: 'head', name: '머리', zoomOrg: 'center 12%', zoomScale: 2.5 },
  chest: { id: 'chest', name: '흉부', zoomOrg: 'center 25%', zoomScale: 2 },
  abdomen: { id: 'abdomen', name: '복부 및 골반', zoomOrg: 'center 45%', zoomScale: 2 },
  back: { id: 'back', name: '허리', zoomOrg: 'center 38%', zoomScale: 2.2 },
  arms: { id: 'arms', name: '팔', zoomOrg: 'center 30%', zoomScale: 1.8 },
  legs: { id: 'legs', name: '다리', zoomOrg: 'center 80%', zoomScale: 2.2 },
};

export const SUB_PARTS = {
  head_main: { name: '머리', group: 'head', symptoms: [{title: '지끈지끈 두통/스트레스', point: '백회혈'}, {title: '머리가 멍하고 어지러움', point: '풍지혈'}] },
  eyes: { name: '눈', group: 'head', symptoms: [{title: '눈 피로/침침함', point: '찬죽혈'}, {title: '눈 충혈/건조함', point: '태양혈'}, {title: '눈 떨림/안면 경련', point: '사백혈'}] },
  neck: { name: '목', group: 'head', symptoms: [{title: '뒷목 뻐근함/거북목', point: '견정혈'}] },
  shoulder_l: { name: '왼쪽 어깨', group: 'chest', symptoms: [{title: '어깨 결림/오십견', point: '견정혈'}, {title: '어깨 뭉침/통증', point: '천종혈'}] },
  shoulder_r: { name: '오른쪽 어깨', group: 'chest', symptoms: [{title: '어깨 결림/오십견', point: '견정혈'}, {title: '어깨 뭉침/통증', point: '천종혈'}] },
  chest_main: { name: '가슴', group: 'chest', symptoms: [{title: '가슴 답답함/화병', point: '단중혈'}, {title: '호흡이 얕고 불안함', point: '전중혈'}] },
  abdomen_main: { name: '상복부', group: 'abdomen', symptoms: [{title: '소화불량/급체', point: '중완혈'}, {title: '속쓰림/위장장애', point: '거궐혈'}] },
  pelvis: { name: '하복부/골반', group: 'abdomen', symptoms: [{title: '생리통/아랫배 냉증', point: '관원혈(단전)'}, {title: '변비/장 기능 저하', point: '천추혈'}] },
  back_upper: { name: '등(상부)', group: 'back', symptoms: [{title: '등 뻐근함/담 결림', point: '풍문혈'}] },
  back_lower: { name: '허리', group: 'back', symptoms: [{title: '만성 허리 통증', point: '신수혈'}, {title: '허리 삐끗/급성 요통', point: '요양관혈'}, {title: '좌골신경통/엉덩이 통증', point: '환도혈'}] },
  arm_upper_l: { name: '왼쪽 윗팔', group: 'arms', symptoms: [{title: '어깨부터 팔까지 저림', point: '견우혈'}] },
  arm_lower_l: { name: '왼쪽 아랫팔', group: 'arms', symptoms: [{title: '팔목 시큰거림', point: '수삼리혈'}, {title: '손목터널증후군', point: '내관혈'}] },
  hand_l: { name: '왼손', group: 'arms', symptoms: [{title: '체했을 때 (만병통치)', point: '합곡혈'}, {title: '수족냉증/긴장 완화', point: '노궁혈'}] },
  arm_upper_r: { name: '오른쪽 윗팔', group: 'arms', symptoms: [{title: '어깨부터 팔까지 저림', point: '견우혈'}] },
  arm_lower_r: { name: '오른쪽 아랫팔', group: 'arms', symptoms: [{title: '팔목 시큰거림', point: '수삼리혈'}, {title: '손목터널증후군', point: '내관혈'}] },
  hand_r: { name: '오른손', group: 'arms', symptoms: [{title: '체했을 때 (만병통치)', point: '합곡혈'}, {title: '수족냉증/긴장 완화', point: '노궁혈'}] },
  leg_upper_l: { name: '왼쪽 허벅지', group: 'legs', symptoms: [{title: '허벅지 피로감/저림', point: '풍시혈'}] },
  leg_lower_l: { name: '왼쪽 종아리', group: 'legs', symptoms: [{title: '다리 부종/밤에 쥐날 때', point: '승산혈'}, {title: '하체 무력감/피로', point: '족삼리혈'}] },
  foot_l: { name: '왼발', group: 'legs', symptoms: [{title: '발바닥/전신 피로 회복', point: '용천혈'}, {title: '불면증/마음 안정', point: '태충혈'}] },
  leg_upper_r: { name: '오른쪽 허벅지', group: 'legs', symptoms: [{title: '허벅지 피로감/저림', point: '풍시혈'}] },
  leg_lower_r: { name: '오른쪽 종아리', group: 'legs', symptoms: [{title: '다리 부종/밤에 쥐날 때', point: '승산혈'}, {title: '하체 무력감/피로', point: '족삼리혈'}] },
  foot_r: { name: '오른발', group: 'legs', symptoms: [{title: '발바닥/전신 피로 회복', point: '용천혈'}, {title: '불면증/마음 안정', point: '태충혈'}] },
};

export const SVG_PATHS = [
  { id: 'head_main', d: 'M175,60 C175,20 225,20 225,60 C225,100 210,110 200,110 C190,110 175,100 175,60 Z' },
  { id: 'eyes', d: 'M185,54 C185,48 196,48 196,54 C196,60 185,60 185,54 Z M204,54 C204,48 215,48 215,54 C215,60 204,60 204,54 Z' },
  { id: 'neck', d: 'M185,100 L215,100 L220,135 L180,135 Z' },
  { id: 'shoulder_l', d: 'M140,130 L180,130 C165,133 148,142 130,155 L110,160 C120,145 130,135 140,130 Z' },
  { id: 'shoulder_r', d: 'M260,130 L220,130 C235,133 252,142 270,155 L290,160 C280,145 270,135 260,130 Z' },
  { id: 'chest_main', d: 'M180,130 L220,130 C250,135 260,150 265,170 L245,220 C220,240 180,240 155,220 L135,170 C140,150 150,135 180,130 Z' },
  { id: 'abdomen_main', d: 'M157,215 C180,240 220,240 243,215 L235,295 L165,295 Z' },
  { id: 'pelvis', d: 'M165,290 L235,290 C250,330 230,360 200,380 C170,360 150,330 165,290 Z' },
  { id: 'back_upper', d: 'M125,170 L135,170 L140,215 L130,215 Z M265,170 L275,170 L270,215 L260,215 Z' },
  { id: 'back_lower', d: 'M130,215 L140,215 L148,290 L138,290 Z M260,215 L270,215 L262,290 L252,290 Z' },
  { id: 'arm_upper_l', d: 'M110,160 L90,260 L65,250 L95,155 Z' },
  { id: 'arm_lower_l', d: 'M90,260 L60,340 L40,330 L65,250 Z' },
  { id: 'hand_l', d: 'M60,340 L50,380 L25,370 L40,330 Z' },
  { id: 'arm_upper_r', d: 'M290,160 L310,260 L335,250 L305,155 Z' },
  { id: 'arm_lower_r', d: 'M310,260 L340,340 L360,330 L335,250 Z' },
  { id: 'hand_r', d: 'M340,340 L350,380 L375,370 L360,330 Z' },
  { id: 'leg_upper_l', d: 'M170,345 L190,360 L175,520 L135,510 Z' },
  { id: 'leg_lower_l', d: 'M175,520 L165,660 L125,650 L135,510 Z' },
  { id: 'foot_l', d: 'M165,660 L170,700 L115,690 L125,650 Z' },
  { id: 'leg_upper_r', d: 'M230,345 L210,360 L225,520 L265,510 Z' },
  { id: 'leg_lower_r', d: 'M225,520 L235,660 L275,650 L265,510 Z' },
  { id: 'foot_r', d: 'M235,660 L230,700 L285,690 L275,650 Z' },
];

// 혈자리 상세 정보 (총 28개)
export const POINT_DETAILS = {
  '백회혈': { name: '백회혈 (百會穴, GV20)', location: '정수리 꼭대기', method: '검지와 중지로 부드럽게 원을 그리며 지압', duration: '3~5초간 누르고 2초 쉬기', repetitions: '10~15회 반복', effects: ['긴장성 두통 완화', '스트레스 해소', '정신 맑아짐', '혈액순환 촉진'] },
  '풍지혈': { name: '풍지혈 (風池穴, GB20)', location: '뒷머리 아래 양쪽 움푹 들어간 부분', method: '양쪽 엄지로 두개골 방향으로 눌러줌', duration: '5~7초간 지속 압박', repetitions: '8~10회 반복', effects: ['어지러움 완화', '두통 해소', '목 뒤 긴장 해소', '혈액순환 촉진'] },
  '찬죽혈': { name: '찬죽혈 (攢竹穴, BL2)', location: '눈썹 안쪽 끝 움푹 파인 곳', method: '양쪽 엄지로 부드럽게 원을 그리며 지압', duration: '3~5초간 누르기', repetitions: '10~15회 반복', effects: ['눈 피로 해소', '시력 보호', '두통 완화', '눈 주위 혈행 촉진'] },
  '태양혈': { name: '태양혈 (太陽穴, EX-HN5)', location: '관자놀이 움푹 파인 부분', method: '양쪽 검지로 부드럽게 원형 마사지', duration: '5~7초간 부드럽게 누르기', repetitions: '10~15회 반복', effects: ['눈 충혈 완화', '안구 건조 개선', '편두통 완화', '눈 주위 긴장 해소'] },
  '사백혈': { name: '사백혈 (四白穴, ST2)', location: '눈 아래뼈에서 약 2cm 아래', method: '검지로 부드럽게 누르기', duration: '3~5초간 부드럽게 누르기', repetitions: '10~12회 반복', effects: ['눈 떨림 완화', '안면 경련 해소', '눈 피로 회복', '안면 혈행 촉진'] },
  '견정혈': { name: '견정혈 (肩井穴, GB21)', location: '목과 어깨 끝의 중간 지점', method: '반대편 손 중지로 강하게 누르기', duration: '5~7초간 누르기', repetitions: '8~10회 반복 (양쪽)', effects: ['뒷목 뻐근함 해소', '거북목 통증 완화', '어깨 결림 해소', '상체 혈액순환'] },
  '천종혈': { name: '천종혈 (天宗穴, SI11)', location: '견갑골(날개뼈) 중앙 움푹 파인 곳', method: '테니스공 또는 반대편 손으로 누르기', duration: '5~7초간 누르기', repetitions: '10~15회 반복 (양쪽)', effects: ['어깨 뭉침 해소', '견갑골 통증 완화', '상체 혈행 촉진', '어깨 유연성 개선'] },
  '단중혈': { name: '단중혈 (膻中穴, CV17)', location: '양쪽 유두 연결선의 정중앙', method: '검지와 중지로 부드럽게 원형으로 문지르기', duration: '5초간 누르기', repetitions: '10~15회 반복', effects: ['가슴 답답함 해소', '화병 완화', '기혈 순환 촉진', '정서 안정'] },
  '전중혈': { name: '전중혈 (前中穴)', location: '흉골 중앙부, 단중혈 약간 위쪽', method: '손바닥으로 따뜻하게 감싸며 시계방향 문지르기', duration: '7~10초간 부드럽게 누르기', repetitions: '10~12회 반복', effects: ['호흡 안정', '불안감 해소', '심장 기능 안정', '스트레스 완화'] },
  '중완혈': { name: '중완혈 (中脘穴, CV12)', location: '배꼽과 명치의 정중앙', method: '손바닥으로 시계 방향 부드럽게 문지르기', duration: '5~10초간 부드럽게 누르기', repetitions: '15~20회 반복', effects: ['소화 촉진', '위장 기능 강화', '속쓰림 완화', '복부 불쾌감 해소'] },
  '거궐혈': { name: '거궐혈 (巨闕穴, CV14)', location: '명치 바로 아래', method: '검지와 중지로 부드럽게 누르기, 식후 30분 후 시행', duration: '3~5초간 누르기', repetitions: '10~12회 반복', effects: ['속쓰림 완화', '위산 역류 개선', '위장 기능 안정', '소화 촉진'] },
  '관원혈(단전)': { name: '관원혈 (關元穴, CV4)', location: '배꼽 아래 약 7cm', method: '손바닥으로 따뜻하게 시계방향 누르기', duration: '7~10초간 지속 압박', repetitions: '10~15회 반복', effects: ['생리통 완화', '하복부 냉증 개선', '자궁 건강', '기력 회복'] },
  '천추혈': { name: '천추혈 (天樞穴, ST25)', location: '배꼽 양옆 약 4cm', method: '검지와 중지로 배꼽 양쪽 동시에 누르기', duration: '5~7초간 부드럽게 누르기', repetitions: '15~20회 반복', effects: ['변비 해소', '장 기능 활성화', '복부 팽만감 완화', '소화 촉진'] },
  '풍문혈': { name: '풍문혈 (風門穴, BL12)', location: '등 위쪽, 제2 흉추 양옆 약 3cm', method: '테니스공 두 개로 등 아래 굴리기', duration: '5~7초간 누르기', repetitions: '10~12회 반복', effects: ['등 뻐근함 해소', '담 결림 완화', '감기 예방', '풍기 배출'] },
  '신수혈': { name: '신수혈 (腎兪穴, BL23)', location: '허리 양쪽, 배꼽 높이 양옆 약 3cm', method: '양손 주먹으로 허리를 두드리거나 엄지로 누르기', duration: '5~10초간 지속 압박', repetitions: '15~20회 반복', effects: ['만성 허리 통증 완화', '신장 기능 강화', '기력 회복', '하체 냉증 개선'] },
  '요양관혈': { name: '요양관혈 (腰陽關穴, GV3)', location: '허리 정중앙, 골반 높이 척추 중앙', method: '엄지 또는 손바닥으로 따뜻하게 누르기', duration: '7~10초간 지속 압박', repetitions: '10~15회 반복', effects: ['급성 요통 완화', '허리 유연성 개선', '하체 혈행 촉진', '양기 보충'] },
  '환도혈': { name: '환도혈 (環跳穴, GB30)', location: '엉덩이 바깥쪽', method: '테니스공 위에 엉덩이를 올려 체중으로 누르기', duration: '5~7초간 누르기', repetitions: '10~12회 반복 (양쪽)', effects: ['좌골신경통 완화', '엉덩이 통증 해소', '하지 혈행 촉진', '고관절 유연성 개선'] },
  '견우혈': { name: '견우혈 (肩髃穴, LI15)', location: '어깨 끝 앞쪽 오목한 곳', method: '반대편 엄지로 꾹 누르기', duration: '5초간 누르고 3초 쉬기', repetitions: '10~12회 반복 (양쪽)', effects: ['어깨~팔 저림 완화', '어깨 통증 해소', '상지 혈행 촉진', '관절 유연성 개선'] },
  '수삼리혈': { name: '수삼리혈 (手三里穴, LI10)', location: '팔꿈치 바깥쪽에서 손목 방향 약 5cm', method: '반대편 엄지로 세게 누르기', duration: '5~7초간 누르기', repetitions: '10~15회 반복 (양쪽)', effects: ['팔목 통증 완화', '팔 피로 해소', '소화 기능 보조', '상지 혈행 촉진'] },
  '내관혈': { name: '내관혈 (內關穴, PC6)', location: '손목 안쪽에서 팔꿈치 방향 약 5cm, 두 힘줄 사이', method: '반대 손 엄지로 부드럽게 누르기', duration: '3~5초간 누르기', repetitions: '10~15회 반복 (양손)', effects: ['손목 통증 완화', '멀미/메스꺼움 해소', '심장 안정', '정서 안정'] },
  '합곡혈': { name: '합곡혈 (合谷穴, LI4)', location: '엄지와 검지 사이 물갈퀴 부분', method: '반대 손 엄지와 검지로 강하게 누르기', duration: '5~7초간 누르기', repetitions: '10~15회 반복 (양손)', effects: ['체기 해소 (만병통치혈)', '두통·치통 완화', '면역력 강화', '전신 기혈 순환'] },
  '노궁혈': { name: '노궁혈 (勞宮穴, PC8)', location: '손바닥 한가운데', method: '반대쪽 엄지로 꾹 누르기', duration: '3~5초간 누르기', repetitions: '15~20회 반복 (양손)', effects: ['수족냉증 개선', '손 혈액순환 촉진', '긴장 완화', '마음 안정'] },
  '풍시혈': { name: '풍시혈 (風市穴, GB31)', location: '차렷 자세에서 중지 끝이 닿는 허벅지 바깥쪽', method: '주먹으로 두드리거나 엄지로 누르기', duration: '5초간 누르기', repetitions: '10~15회 반복 (양쪽)', effects: ['허벅지 피로 해소', '하지 저림 완화', '하체 혈행 촉진', '풍기 제거'] },
  '승산혈': { name: '승산혈 (承山穴, BL57)', location: '종아리 뒤쪽 중간 V자 지점', method: '엄지로 천천히 강하게 누르기', duration: '5~7초간 누르기', repetitions: '10~15회 반복 (양쪽)', effects: ['다리 부종 완화', '종아리 피로 해소', '혈액순환 촉진', '다리 쥐남 방지'] },
  '족삼리혈': { name: '족삼리혈 (足三里穴, ST36)', location: '무릎뼈 바깥쪽 아래에서 약 7cm', method: '엄지로 세게 누르기', duration: '5~7초간 누르기', repetitions: '10~15회 반복 (양쪽)', effects: ['하체 무력감 해소', '소화 기능 강화', '체력 증진', '면역력 향상'] },
  '용천혈': { name: '용천혈 (湧泉穴, KI1)', location: '발바닥 앞쪽 1/3 지점', method: '엄지로 강하게 누르기, 취침 전 추천', duration: '5~7초간 누르기', repetitions: '15~20회 반복 (양발)', effects: ['전신 피로 회복', '발바닥 통증 완화', '신장 기능 강화', '하체 냉증 개선'] },
  '태충혈': { name: '태충혈 (太衝穴, LR3)', location: '발등, 엄지와 둘째 발가락 사이 뼈가 만나는 곳', method: '엄지로 V자 뼈 사이 누르기, 취침 전 추천', duration: '3~5초간 누르기', repetitions: '15~20회 반복 (양발)', effects: ['불면증 개선', '스트레스 해소', '간 기능 안정', '마음 안정·이완'] },
};
